apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viz-workflow-sa-role
  namespace: viz-workflow
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
